// cafes.js — datos de los 8 cafés del catálogo demo

const CAFES = [
  {
    id: "espresso",
    name: "Espresso",
    italic: "il classico",
    tag: "El origen",
    blurb: "30 ml. 25 segundos. El café en su forma más concentrada.",
    intensity: 5, body: 5, acidez: 3, dulzor: 2,
    notas: ["Cacao", "Caramelo", "Tabaco"],
    receta: ["18 g de café molido fino", "25–30 s de extracción", "30 ml de líquido en taza"],
    ratio: "1:2", temp: "93°C", time: "25s",
    color: "#3A2418",
  },
  {
    id: "ristretto",
    name: "Ristretto",
    italic: "il breve",
    tag: "Más corto, más intenso",
    blurb: "La mitad de agua, el doble de carácter. Pura concentración.",
    intensity: 5, body: 5, acidez: 4, dulzor: 3,
    notas: ["Chocolate amargo", "Especias"],
    receta: ["18 g de café fino", "15–20 s de extracción", "15–20 ml por taza"],
    ratio: "1:1", temp: "93°C", time: "18s",
    color: "#2A1810",
  },
  {
    id: "americano",
    name: "Americano",
    italic: "il lungo",
    tag: "Para tomar despacio",
    blurb: "Un espresso encontrado con agua caliente. Largo y honesto.",
    intensity: 3, body: 3, acidez: 3, dulzor: 3,
    notas: ["Nuez", "Madera", "Pan tostado"],
    receta: ["1 espresso de 30 ml", "120 ml de agua a 90°C", "Servir con la crema arriba"],
    ratio: "1:5", temp: "90°C", time: "30s",
    color: "#5C3A1F",
  },
  {
    id: "cortado",
    name: "Cortado",
    italic: "il equilibrio",
    tag: "El más rioplatense",
    blurb: "Espresso 'cortado' con la misma cantidad de leche texturizada.",
    intensity: 4, body: 4, acidez: 2, dulzor: 4,
    notas: ["Leche caliente", "Toffee", "Almendra"],
    receta: ["1 espresso", "30 ml leche vaporizada a 60°C", "Microespuma muy fina"],
    ratio: "1:1", temp: "60°C", time: "30s",
    color: "#7C4A20",
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    italic: "il classico mattino",
    tag: "Tres tercios perfectos",
    blurb: "Un tercio espresso, un tercio leche, un tercio espuma.",
    intensity: 3, body: 4, acidez: 2, dulzor: 4,
    notas: ["Leche cremosa", "Cacao", "Vainilla"],
    receta: ["1 espresso", "60 ml leche vaporizada", "60 ml espuma densa", "Cacao en polvo a gusto"],
    ratio: "1:2:2", temp: "65°C", time: "45s",
    color: "#9A6936",
  },
  {
    id: "flat-white",
    name: "Flat White",
    italic: "il moderno",
    tag: "Australiano. Sedoso.",
    blurb: "Doble ristretto + microespuma sin burbujas. Café que abraza.",
    intensity: 4, body: 4, acidez: 3, dulzor: 3,
    notas: ["Caramelo", "Crema", "Avellana"],
    receta: ["Doble ristretto (40 ml)", "120 ml leche con microespuma de 4 mm", "Vertido lento desde altura baja"],
    ratio: "1:3", temp: "60°C", time: "40s",
    color: "#6F4220",
  },
  {
    id: "latte",
    name: "Latte",
    italic: "il gentile",
    tag: "Suave, largo, cremoso",
    blurb: "Más leche que ningún otro. Ideal para arte latte.",
    intensity: 2, body: 3, acidez: 1, dulzor: 5,
    notas: ["Leche dulce", "Bizcocho", "Vainilla"],
    receta: ["1 espresso (30 ml)", "180 ml leche vaporizada", "Capa fina de espuma (1 cm)"],
    ratio: "1:6", temp: "60°C", time: "50s",
    color: "#B58659",
  },
  {
    id: "mocha",
    name: "Mocha",
    italic: "la dolce vita",
    tag: "Café + chocolate",
    blurb: "Donde el café se vuelve postre sin perder la fuerza.",
    intensity: 3, body: 4, acidez: 2, dulzor: 5,
    notas: ["Chocolate", "Crema batida", "Naranja confitada"],
    receta: ["1 espresso", "20 ml jarabe de chocolate", "150 ml leche vaporizada", "Crema y cacao por encima"],
    ratio: "1:1:5", temp: "60°C", time: "60s",
    color: "#4A2516",
  },
];

window.CAFES = CAFES;
